packages:
  - apps/*
  - packages/*
allowBuilds:
  bufferutil: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - utf-8-validate
